from alembic import context
# flake8: noqa
"""empty message

Revision ID: 22abc7aa0af
Revises: 43dc41b81ae
Create Date: 2017-07-07 07:25:41.940604

"""

# revision identifiers, used by Alembic.
revision = '22abc7aa0af'
down_revision = '43dc41b81ae'

from alembic import op, context
import sqlalchemy as sa
import os


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrower', sa.Column('signing_in_progress', sa.Boolean(), nullable=True))
    op.add_column('deed', sa.Column('deed_hash', sa.String(), nullable=True))
    ### end Alembic commands ###

    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE \
                    ON borrower, deed, mortgage_document, naa_audit, verify_match \
                    TO " + str(os.getenv('APP_SQL_USERNAME')))

    context.execute("GRANT USAGE, SELECT ON SEQUENCE borrower_id_seq, deed_id_seq, naa_audit_id_seq\
                    TO " + str(os.getenv('APP_SQL_USERNAME')))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'deed_hash')
    op.drop_column('borrower', 'signing_in_progress')
    ### end Alembic commands ###

    context.execute("REVOKE SELECT, UPDATE, INSERT, DELETE \
                    ON borrower, deed, mortgage_document, naa_audit, verify_match \
                    TO " + str(os.getenv('APP_SQL_USERNAME')))

    context.execute("REVOKE USAGE, SELECT ON SEQUENCE borrower_id_seq, deed_id_seq, naa_audit_id_seq\
                    TO " + str(os.getenv('APP_SQL_USERNAME')))
