# flake8: noqa
"""empty message

Revision ID: 22abc7aa0af
Revises: 4207bf4d10a
Create Date: 2017-07-07 07:25:41.940604

"""

# revision identifiers, used by Alembic.
revision = '22abc7aa0af'
down_revision = '4207bf4d10a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrower', sa.Column('signing_in_progress', sa.Boolean(), nullable=True))
    op.add_column('deed', sa.Column('deed_hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'deed_hash')
    op.drop_column('borrower', 'signing_in_progress')
    ### end Alembic commands ###
