# flake8: noqa
"""Added in identity checked column to ensure that conveyancers can declare that they have checked borrowers identities

Revision ID: 2ef609ed309
Revises: 610e8a67d8
Create Date: 2016-01-15 16:17:47.746339

"""

# revision identifiers, used by Alembic.
revision = '2ef609ed309'
down_revision = '610e8a67d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('identity_checked', sa.String(length=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'identity_checked')
    ### end Alembic commands ###
