# flake8: noqa
"""empty message

Revision ID: 32bb5582712
Revises: 3e06856fdac
Create Date: 2016-11-28 13:46:24.810120

"""

# revision identifiers, used by Alembic.
revision = '32bb5582712'
down_revision = '3e06856fdac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify_match',
    sa.Column('verify_pid', sa.String(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ),
    sa.PrimaryKeyConstraint('verify_pid', 'borrower_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify_match')
    ### end Alembic commands ###
