"""added esec_user_name

Revision ID: 33280da2569
Revises: 384b88178a6
Create Date: 2016-03-04 09:33:22.187200

"""

# revision identifiers, used by Alembic.
revision = '33280da2569'
down_revision = '384b88178a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrower', sa.Column('esec_user_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrower', 'esec_user_name')
    ### end Alembic commands ###
