# flake8: noqa
"""empty message

Revision ID: 35537405c34
Revises: 4207bf4d10a
Create Date: 2017-07-13 10:36:33.905842

"""

# revision identifiers, used by Alembic.
revision = '35537405c34'
down_revision = '4207bf4d10a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'organisation_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('organisation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
