# flake8: noqa
"""empty message

Revision ID: 384b88178a6
Revises: 34e2c47a334
Create Date: 2016-02-16 16:53:38.614799

"""

# revision identifiers, used by Alembic.
revision = '384b88178a6'
down_revision = '58a0624da37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('checksum', sa.Integer(), nullable=True))
    op.add_column('deed', sa.Column('deed_xml', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'deed_xml')
    op.drop_column('deed', 'checksum')
    ### end Alembic commands ###
