"""empty message

Revision ID: 3e06856fdac
Revises: 48bd8328605
Create Date: 2016-11-28 13:44:44.089867

"""

# revision identifiers, used by Alembic.
revision = '3e06856fdac'
down_revision = '48bd8328605'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify_match')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify_match',
    sa.Column('verify_pid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], name='verify_match_borrower_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verify_pid', 'borrower_id', name='verify_match_pkey')
    )
    ### end Alembic commands ###
