# flake8: noqa
"""empty message

Revision ID: 3e92812b8a9
Revises: 7aff0b2340
Create Date: 2015-11-18 15:55:46.264888

"""

# revision identifiers, used by Alembic.
revision = '3e92812b8a9'
down_revision = '7aff0b2340'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('uid', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'uid')
    ### end Alembic commands ###
