"""empty message

Revision ID: 3fea2a84b1
Revises: 48bd8328605
Create Date: 2016-11-22 10:35:46.321430

"""

# revision identifiers, used by Alembic.
revision = '3fea2a84b1'
down_revision = '48bd8328605'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verify_match', 'confidence_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('verify_match_borrower_id_fkey', 'verify_match', type_='foreignkey')
    op.create_foreign_key(None, 'verify_match', 'borrower', ['borrower_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verify_match', type_='foreignkey')
    op.create_foreign_key('verify_match_borrower_id_fkey', 'verify_match', 'borrower', ['borrower_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verify_match', 'confidence_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
