# flake8: noqa
"""empty message

Revision ID: 4207bf4d10a
Revises: 4b7f33855ed
Create Date: 2017-05-10 15:09:43.868757

"""

# revision identifiers, used by Alembic.
revision = '4207bf4d10a'
down_revision = '4b7f33855ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'verify_match', 'borrower', ['borrower_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verify_match', type_='foreignkey')
    ### end Alembic commands ###
