# flake8: noqa

"""empty message

Revision ID: 43dc41b81ae
Revises: 4207bf4d10a
Create Date: 2017-07-13 12:22:09.973936

"""

# revision identifiers, used by Alembic.
revision = '43dc41b81ae'
down_revision = '4207bf4d10a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortgage_document', sa.Column('legal_warning', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortgage_document', 'legal_warning')
    ### end Alembic commands ###
