"""empty message

Revision ID: 472fc0f973c
Revises: 34e2c47a334
Create Date: 2016-02-16 16:17:22.745338

"""

# revision identifiers, used by Alembic.
revision = '472fc0f973c'
down_revision = '34e2c47a334'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('checksum', sa.Integer(), nullable=True))
    op.add_column('deed', sa.Column('deed_xml', sa.BLOB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'deed_xml')
    op.drop_column('deed', 'checksum')
    ### end Alembic commands ###
