# flake8: noqa
"""empty message

Revision ID: 48bd8328605
Revises: 4df196169dc
Create Date: 2016-10-12 08:45:16.198965

"""

# revision identifiers, used by Alembic.
revision = '48bd8328605'
down_revision = '4df196169dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naa_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('date_accepted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('naa_audit')
    ### end Alembic commands ###
