"""empty message

Revision ID: 48bd8328605
Revises: 4df196169dc
Create Date: 2016-10-12 08:45:16.198965

"""

# revision identifiers, used by Alembic.
revision = '48bd8328605'
down_revision = '4df196169dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naa_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('date_accepted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('verify_match_borrower_id_fkey', 'verify_match', type_='foreignkey')
    op.create_foreign_key(None, 'verify_match', 'borrower', ['borrower_id'], ['id'])
    op.drop_column('verify_match', 'confidence_level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verify_match', sa.Column('confidence_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'verify_match', type_='foreignkey')
    op.create_foreign_key('verify_match_borrower_id_fkey', 'verify_match', 'borrower', ['borrower_id'], ['id'], ondelete='CASCADE')
    op.drop_table('naa_audit')
    ### end Alembic commands ###
