# flake8: noqa
"""Add verify match table

Revision ID: 4df196169dc
Revises: 33280da2569
Create Date: 2016-03-23 15:20:22.930213

"""

# revision identifiers, used by Alembic.
revision = '4df196169dc'
down_revision = '33280da2569'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify_match',
    sa.Column('verify_pid', sa.String(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ),
    sa.PrimaryKeyConstraint('verify_pid', 'borrower_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify_match')
    ### end Alembic commands ###
