"""empty message

Revision ID: 5a0030d4756
Revises: 48bd8328605
Create Date: 2017-05-02 12:47:15.120148

"""

# revision identifiers, used by Alembic.
revision = '5a0030d4756'
down_revision = '48bd8328605'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('created_date', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    op.add_column('deed', sa.Column('payload_json', postgresql.JSON(), nullable=True))
    op.drop_constraint('verify_match_borrower_id_fkey', 'verify_match', type_='foreignkey')
    op.create_foreign_key(None, 'verify_match', 'borrower', ['borrower_id'], ['id'])
    op.drop_column('verify_match', 'confidence_level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verify_match', sa.Column('confidence_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'verify_match', type_='foreignkey')
    op.create_foreign_key('verify_match_borrower_id_fkey', 'verify_match', 'borrower', ['borrower_id'], ['id'], ondelete='CASCADE')
    op.drop_column('deed', 'payload_json')
    op.drop_column('deed', 'created_date')
    ### end Alembic commands ###
