# flake8: noqa
"""empty message

Revision ID: 610e8a67d8
Revises: 645733c7c2
Create Date: 2016-01-07 11:31:21.939196

"""

# revision identifiers, used by Alembic.
revision = '610e8a67d8'
down_revision = '645733c7c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('borrower', sa.Column('token', sa.String(), nullable=False))
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('borrower', 'token')
    # end Alembic commands #
