# flake8: noqa
"""empty message

Revision ID: 7aff0b2340
Revises: None
Create Date: 2015-11-09 14:00:23.606372

"""

# revision identifiers, used by Alembic.
revision = '7aff0b2340'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deed', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deed')
    ### end Alembic commands ###
