"""empty message

Revision ID: 9d8d081eb5
Revises: 4207bf4d10a
Create Date: 2017-06-22 14:17:46.925088

"""

# revision identifiers, used by Alembic.
revision = '9d8d081eb5'
down_revision = '4207bf4d10a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deed', sa.Column('deed_hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deed', 'deed_hash')
    ### end Alembic commands ###
