"""empty message

Revision ID: cfe2e2f325
Revises: 610e8a67d8
Create Date: 2016-01-15 15:43:21.906528

"""

# revision identifiers, used by Alembic.
revision = 'cfe2e2f325'
down_revision = '610e8a67d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mortgage_document',
    sa.Column('md_ref', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('md_ref')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mortgage_document')
    ### end Alembic commands ###
