"""empty message

Revision ID: eb2745f554
Revises: 5a0030d4756
Create Date: 2017-05-09 11:25:21.851263

"""

# revision identifiers, used by Alembic.
revision = 'eb2745f554'
down_revision = '5a0030d4756'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('verify_match_borrower_id_fkey', 'verify_match', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('verify_match_borrower_id_fkey', 'verify_match', 'borrower', ['borrower_id'], ['id'])
    ### end Alembic commands ###
